# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/react-dom"
      - dependency-name: "react-dom"
      - dependency-name: "@strapi/plugin-cloud"
      - dependency-name: "@strapi/strapi"
      - dependency-name: "react-router-dom"
      - dependency-name: "jsdom"
      - dependency-name: "@strapi/provider-email-nodemailer"
